# Generated by Django 5.1.7 on 2025-03-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltag',
            name='skill_image',
            field=models.ImageField(default='static/skill_icons/code.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='skilltag',
            name='skill_name',
            field=models.CharField(max_length=30),
        ),
    ]
