# Generated by Django 5.1.7 on 2025-03-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_skilltag_skill_image_alter_skilltag_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltag',
            name='skill_image',
            field=models.ImageField(default='media/images/code.png', upload_to='images/'),
        ),
    ]
