# Generated by Django 5.1.7 on 2025-03-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_project_alter_skilltag_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='myRole',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.JSONField(default=list, null=True),
        ),
    ]
