# Generated by Django 5.1.7 on 2025-03-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_project_description_alter_project_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.JSONField(default=list),
        ),
    ]
