# Generated by Django 5.1.7 on 2025-03-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_project_description_alter_project_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(default='#', max_length=500, null=True),
        ),
    ]
