# Generated by Django 5.1.7 on 2025-03-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
