# Generated by Django 5.1.7 on 2025-03-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_project_link_alter_project_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, default='#', max_length=500, null=True),
        ),
    ]
